image:
  name: klakegg/hugo:alpine-ci 
  entrypoint: ["hugo-official"]
  
master-build:
  stage: build
  script:
    - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  interruptible: true

master-deploy:
  stage: deploy
  before_script:
    # Install expect
    - apk add expect

    # Set up keys
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$NEW_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # Load key with passphrase
    - eval $(ssh-agent -s)
    - expect -c 'spawn ssh-add /root/.ssh/id_rsa; expect "Enter passphrase for /root/.ssh/id_rsa:"; send "$env(NEW_KEY_PASSPHRASE)\r"; expect eof'

    # Set up known hosts
    - echo "$NEW_KNOWN_HOST" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    # Backup old version
    - ssh hvoajxlo@185.165.170.81 '/home/hvoajxlo/bin/backup_hugo'
    
    # Transfer files
    - rsync -aq -delete -e ssh -z -r public/ hvoajxlo@185.165.170.81:/home/hvoajxlo/upload/

    # Move new files into place
    - ssh hvoajxlo@185.165.170.81 '/home/hvoajxlo/bin/sync_hugo'

  only:
    - master
