baseURL: "https://dev.xrebellion.ch/"
languageCode: "en-us"
title: "XR Switzerland"

taxonomies:
  category: categories
  tag: tags
  branch: branch
  event_type: event_type
  resource_type: resource_types
  faq_type: faq_types
  principles_type: principles_types

defaultContentLanguage: de
languages:
  en:
    languageName: "EN"
    weight: 1
  fr:
    languageName: "FR"
    weight: 2
  de:
    languageName: "DE"
    weight: 3
  it:
    languageName: "IT"
    weight: 4
