backend:
  name: gitlab
  repo: xr-switzerland/hugo-web # Path to your GitLab repository
  branch: master # Branch to update
  auth_type: implicit # Required for implicit grant
  api_root: https://code.organise.earth/api/v4
  app_id: e610c2086aa2c44e75b8fc2221b6a12bfa4693bbd56f8fbe3e675a41eece7c62 # Application ID from GitLab settings
  base_url: https://code.organise.earth
  auth_endpoint: oauth/authorize # This line should *not* be indented
media_folder: static/media
public_folder: /media
collections:
  - name: "events"
    identifier_field: slug
    label: "Events"
    folder: "content/act/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.{{lang}}"
    fields:
      - {label: "Layout", name: "type", widget: "hidden", default: "events"}
      - label: "Language"
        name: "lang"
        widget: "select"
        multiple: false
        options: ["en", "fr", "de", "it"]
        required: true
      - {label: "Titel", name: "title", widget: "string"}
      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true
        hint: "If you're creating the post via the Netlify CMS you must set the `slug` parameter, it must be the same for every translation of the post, otherwise you will have duplicates."
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Branch", name: "branch", widget: "string"}
      - label: "Publishing date and time (should not be in the future)"
        name: "publishdate"
        widget: "datetime"
        required: true
        timeFormat: "HH:mm"
        format: "YYYY-MM-DDTHH:mm:ss+0200"
        pickerUtc: false
      - label: "Event date"
        name: "date"
        widget: "datetime"
        required: true
        timeFormat: "HH:mm"
        format: "YYYY-MM-DDTHH:mm:ss+0200"
        pickerUtc: false
      - label: "Event location name"
        name: "event_loc_name"
        widget: "string"
        required: false
      - label: "Street name"
        name: "event_loc_street_name"
        widget: "string"
        required: false
      - label: "Street number"
        name: "event_loc_street_num"
        widget: "string"
        required: false
      - label: "City"
        name: "event_loc_addressLocality"
        widget: "string"
        required: false
      - label: "Region"
        name: "event_loc_addressRegion"
        widget: "string"
        required: false
      - label: "Zip code"
        name: "event_loc_postalCode"
        widget: "string"
        required: false
      - {label: "Country", name: "event_loc_country", widget: "string", required: false, default: "Switzerland"}
      - label: "Type of event"
        name: "event_type"
        widget: "select"
        multiple: false
        options: ["welcome", "talk", "meeting", "nvda", "action"]
        required: true
      - label: "Image"
        name: "image"
        widget: "file"
        required: false
        media_folder: '{{media_folder}}/events'
        public_folder: '{{public_folder}}/events'
      - label: "Thumb"
        name: "thumb"
        widget: "file"
        required: true
        hint: "This image will be shown on the event page and on top of the event itself."
        media_folder: '{{media_folder}}/events'
        public_folder: '{{public_folder}}/events'
      - label: 'Published'
        name: 'published'
        hint: "Set this to false to unpublish a post"
        widget: "boolean"
        required: false
        default: true
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'news'
    identifier_field: slug
    label: 'News'
    folder: 'content/news'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.{{lang}}"
    fields:
      - {label: "Layout", name: "type", widget: "hidden", default: "blogpost"}
      - label: "Language"
        name: "lang"
        widget: "select"
        multiple: false
        options: ["en", "fr", "de", "it"]
        required: true
      - {label: "Titel", name: "title", widget: "string"}
      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true
        hint: "If you're creating the post via the Netlify CMS you must set the `slug` parameter, it must be the same for every translation of the post, otherwise you will have duplicates."
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Branch", name: "branch", widget: "string"}
      - label: "Publishing date (should not be in the future)"
        name: "publishdate"
        widget: "datetime"
        required: true
        timeFormat: "HH:mm"
        format: "YYYY-MM-DDTHH:mm:ss+0200"
        pickerUtc: false
      - label: "Image"
        name: "image"
        widget: "file"
        required: false
        media_folder: '{{media_folder}}/news'
        public_folder: '{{public_folder}}/news'
      - label: "Thumb"
        name: "thumb"
        widget: "file"
        required: false
        hint: "This image will be shown on the event page and on top of the event itself."
        media_folder: '{{media_folder}}/news'
        public_folder: '{{public_folder}}/news'
      - label: 'Published'
        name: 'published'
        hint: "Set this to false to unpublish a post"
        widget: "boolean"
        required: false
        default: true
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "local_groups"
    label: "Local groups"
    folder: "content/act/localgroups"
    create: true
    slug: "{{slug}}.{{lang}}"
    fields:
      - label: "Language"
        name: "lang"
        widget: "select"
        multiple: false
        options: ["en", "fr", "de", "it"]
        required: true
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
      - label: "Canton"
        name: "canton"
        widget: "string"
        required: false
      - label: "City"
        name: "city"
        widget: "string"
        required: false
      - label: "Email"
        name: "email"
        widget: "string"
        required: false
      - label: "Links"
        name: "links"
        widget: "object"
        fields:
          - {label: "Others", name: "others", widget: "hidden", default: "[]"}
          - {label: "Website", name: "website", widget: "string", required: false}
          - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Twitter", name: "twitter", widget: "string", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}
  - name: "press_releases"
    identifier_field: slug
    label: "Press releases"
    folder: "content/press/pressreleases"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.{{lang}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "pressreleases"}
      - label: "Language"
        name: "lang"
        widget: "select"
        multiple: false
        options: ["en", "fr", "de", "it"]
        required: true
      - {label: "Titel", name: "title", widget: "string"}
      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true
        hint: "If you're creating the post via the Netlify CMS you must set the `slug` parameter, it must be the same for every translation of the post, otherwise you will have duplicates."
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Branch", name: "branch", widget: "string"}
      - label: "Publishing date (should not be in the future)"
        name: "publishdate"
        widget: "datetime"
        required: true
        timeFormat: "HH:mm"
        format: "YYYY-MM-DDTHH:mm:ss+0200"
        pickerUtc: false
      - label: "Image"
        name: "image"
        widget: "file"
        required: false
        media_folder: '{{media_folder}}/pressreleases'
        public_folder: '{{public_folder}}/pressreleases'
      - label: "Pdf"
        name: "pdf"
        widget: "file"
        required: false
        media_folder: '{{media_folder}}/pressreleases'
        public_folder: '{{public_folder}}/pressreleases'
      - label: "Thumb"
        name: "thumb"
        widget: "file"
        required: false
        hint: "This image will be shown on the event page and on top of the event itself."
        media_folder: '{{media_folder}}/pressreleases'
        public_folder: '{{public_folder}}/pressreleases'
      - label: 'Published'
        name: 'published'
        hint: "Set this to false to unpublish a post"
        widget: "boolean"
        required: false
        default: true
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: "resources"
    label: "Resources"
    folder: "content/act/resources"
    create: true
    slug: "{{slug}}.{{lang}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "resources"}
      - label: "Language"
        name: "lang"
        widget: "select"
        multiple: false
        options: ["en", "fr", "de", "it"]
        required: true
      - {label: "Titel", name: "title", widget: "string"}
      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true
        hint: "If you're creating the post via the Netlify CMS you must set the `slug` parameter, it must be the same for every translation of the post, otherwise you will have duplicates."
      - label: "Type of resource"
        name: "resource_types"
        widget: "select"
        multiple: true
        options: ["intern", "outreach", "self-organization-system", "action", "legal", "media", "technical", "regenerative-culture", "strategy"]
        required: true
      - label: "Thumb"
        name: "thumb"
        widget: "file"
        required: false
        hint: "This image will be shown on the event page and on top of the event itself."
        media_folder: '{{media_folder}}/resources'
        public_folder: '{{public_folder}}/resources'
      - label: "Document"
        name: "document"
        widget: "file"
        required: false
        hint: "Either use a document or a link"
        media_folder: '{{media_folder}}/resources'
        public_folder: '{{public_folder}}/resources'
      - label: "Link"
        name: "link"
        widget: "string"
        required: false
        hint: "Either use a link or a document."
      - label: 'Published'
        name: 'published'
        hint: "Set this to false to unpublish a post"
        widget: "boolean"
        required: false
        default: true
